sudo: required #telling travis that elevated privileges are required
language: generic 
services:
  - docker

before_install:
  - docker build -t kinath/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true kinath/docker-react npm run test -- --coverage