version: '3'
services: 
  web:
    build:
      context: . #where the files should come from (in this case, the current directory)
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app  #This is to specify copy all the contents of the current directory to the /app directory in the container. 
  tests:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules # '-' is used to indicate an array
      - .:/app          
    command: ["npm", "run", "test"] #'command' indicates that 'test' service is going to override the docker file command